POST http://localhost:3003/api/blogs
Content-Type: application/json

{
   "title": "selleriblogi",
    "author": "SelleriSari",
    "url": "sirpannblogi.com",
    "likes": 69420,
    "userId": "61902e11a5807362582f38ce"
}